<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ConnectorPackageVersion Condition="'$(ConnectorPackageVersion)' == ''">0.0.0</ConnectorPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MCEGold.Data.Services.Connector" Version="[$(ConnectorPackageVersion)]" />
  </ItemGroup>

</Project>
